gui-name: "&cShop"
gui-rows: 5
gui-sellitem:
  material: "GOLD_NUGGET"
  displayname: "&cClick to Sell (&a%total%&c)"
gui-item-enumeration-format: "%amount%x &c%material%&r = &a %price%"
message-sold: "&aSold all items for &c%total%&a!" 
# would use essentials worth list. Only activate it if you have essentials installed
use-essentials-worth-list: false
command: "sell"
# sell prices. I suggest to use /ushop setprice in game for adding items.